# Generated by Django 4.1.5 on 2023-06-14 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siscon', '0003_convocatoria_inscripcion_convocatoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodoc', models.CharField(max_length=150)),
                ('vence', models.BooleanField()),
                ('vencedias', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='persona',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion', to='siscon.persona'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Legajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacreacion', models.DateTimeField()),
                ('fechaingreso', models.DateField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siscon.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='siscon.legajo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siscon.persona')),
                ('tipodoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='siscon.tipodoc')),
            ],
        ),
        migrations.CreateModel(
            name='Archivopdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='siscon/documentacion/')),
                ('documentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='siscon.documentacion')),
            ],
        ),
    ]
