# Generated by Django 4.1.5 on 2023-06-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscon', '0005_documentacion_archivo_alter_archivopdf_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentacion',
            name='tipodoc',
        ),
        migrations.AddField(
            model_name='documentacion',
            name='tipodoc',
            field=models.ManyToManyField(blank=True, null=True, to='siscon.tipodoc'),
        ),
    ]
