# Generated by Django 4.1.5 on 2023-06-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscon', '0006_remove_documentacion_tipodoc_documentacion_tipodoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodoc',
            old_name='tipodoc',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='tipodoc',
            field=models.ManyToManyField(blank=True, to='siscon.tipodoc'),
        ),
    ]
