# Generated by Django 4.1.5 on 2023-06-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscon', '0007_rename_tipodoc_tipodoc_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='idarea',
            field=models.IntegerField(choices=[(1, 'Consejo de la Magistratura'), (2, 'Secretaria Administrativa')]),
        ),
    ]
